Repository rajatgoyal715/Puzzle15, pull requests merged in 2019-02, with the labels that each got.

#19 Early release
  .gitignore
  app/build.gradle
  app/google-services.json
  app/release/app-release.apk
  app/release/app-release_v1.apk
  app/release/app-release_v1_v2.apk
  app/release/app-release_v2.apk
  app/release/app.aab
  app/release/output.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/rajatgoyal/puzzle15/adapter/LeaderboardAdapter.java
  app/src/main/java/com/rajatgoyal/puzzle15/model/Leaderboard.java
  app/src/main/java/com/rajatgoyal/puzzle15/ui/GameActivity.java
  app/src/main/java/com/rajatgoyal/puzzle15/ui/MainActivity.java
  app/src/main/java/com/rajatgoyal/puzzle15/view/Tile.java
  app/src/main/java/com/rajatgoyal/puzzle15/widget/Widget.java
  app/src/main/java/com/rajatgoyal/puzzle15/widget/WidgetRemoteViewsFactory.java
  app/src/main/java/com/rajatgoyal/puzzle15/widget/WidgetRemoteViewsService.java
  app/src/main/res/drawable/empty.jpg
  app/src/main/res/drawable/icon.png
  app/src/main/res/drawable/puzzle.png
  app/src/main/res/drawable/sorted.jpg
  app/src/main/res/layout-land/activity_game.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_game_rules.xml
  app/src/main/res/layout/dialog_leaderboard.xml
  app/src/main/res/layout/leaderboard_list_item.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/layout/widget.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/raw/click.mp3
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/games-ids.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/widget_info.xml
  screenshots/Screenshot_1548491258.png
  screenshots/Screenshot_1548491267.png
  screenshots/Screenshot_1548491367.png
  screenshots/Screenshot_1548491371.png
  screenshots/Screenshot_1548491375.png
  screenshots/Screenshot_1548491382.png
  screenshots/Screenshot_1548491388.png
  screenshots/feature-graphic.png
  screenshots/puzzle.png
Labels: enhancement

#27 Gesture enhancement
  app/build.gradle
  app/src/main/java/com/rajatgoyal/puzzle15/ui/GameActivity.java
Labels: enhancement

#31 Fix dialog box cancellation
  app/src/main/java/com/rajatgoyal/puzzle15/ui/GameActivity.java
  build.gradle
Labels: bug

#33 Post Travis CI notifications on multiple channels
  .travis.yml
Labels: enhancement

#35 Check moves in makeMove function
  app/src/main/java/com/rajatgoyal/puzzle15/ui/GameActivity.java
Labels: UI, bug

#28 Resume option
  app/src/main/java/com/rajatgoyal/puzzle15/model/GameMatrix.java
  app/src/main/java/com/rajatgoyal/puzzle15/model/Time.java
  app/src/main/java/com/rajatgoyal/puzzle15/ui/GameActivity.java
  app/src/main/java/com/rajatgoyal/puzzle15/ui/MainActivity.java
  app/src/main/java/com/rajatgoyal/puzzle15/util/SharedPref.java
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: UI, enhancement
